

all:
	gcc main.c -L.. -lcvector -o run.lab -Wl,-rpath=/home/zeeshan/projects/shared_object/cvector
#-L.. -lcvector->l for lib cvector-library name no need of .so for automatcally prefix lib and extension .so placed -L.. from where to take .so file\
#-Wl,-path=/for/exetuning/the/executable/file/dynamic/linker/needs/path/of/lib/


